### ISSUE TITLE
Proper Framework and App implementation with working rendering

### ISSUE THREAD

**Issue by SakulFlee** [SakulFlee/Akimo-Project#69]
**EDIT**
This used to be just porting the graphical connector, after the computing connector port. However, after investigating this further, it seems like the old project layout does **not** work out. Thus, this implements a full framework (`Runtime`) and app (`trait App`) to make using this easier and in an actually working manner.

**TODO**
- [x] App trait
- [x] Framework
- [x] GPU Backend (Compute)
- [x] GPU Backend (Graphical)
- [x] Window & Surface creation
- [x] Window event handling

---

Additionally, this introduces **Android** as a supported platform.
There were some difficult problems encountered while trying to get Android to work, mainly: The ecosystem is broken at the moment. We are using our own Android project now that uses a `NativeActivity` to load the compiled library. Compilation is done via `Gradle` and `Cargo-NDK`.

Android CI will be added in #94.
